name: LastSeenDiscord
version: ${version}
main: com.pinnaclesmp.lastseendiscord.LastSeenDiscordPlugin
api-version: '26.2'
author: Kevin
website: https://pinnaclesmp.org
description: Syncs server member activity status to Discord.
commands:
  lastseendiscord:
    description: Manages LastSeenDiscord configuration and synchronization.
    usage: /<command> reload|sync|recover-create
    permission: lastseendiscord.admin
    aliases: [lsd]
permissions:
  lastseendiscord.admin:
    description: Allows reloading and syncing LastSeenDiscord.
    default: op
